<?php

namespace PBundle\Repository;

use  Doctrine\ORM\Query;

/**
 * PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM PBundle:Partenaire p
                WHERE p.nom LIKE :str')
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function createFindAllQuery()
    {
        return $this->_em->getRepository('PBundle:Partenaire')->createQueryBuilder('p');
    }
}
