<?php

namespace volontaireBundle\Repository;

/**
 * commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentRepository extends \Doctrine\ORM\EntityRepository
{

    function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    public function fiii($x){
        $qry=$this->getEntityManager()
            ->createQuery("SELECT m FROM volontaireBundle:event m WHERE m.event = :x")
            ->setParameter(':x',$x);
        return $qry->getResult();
    }
/********************************************/

    public function findTitreParameter($titre){
        $qry=$this->getEntityManager()
            ->createQuery("SELECT m FROM volontaireBundle:event m WHERE m.titre = :tit")
            ->setParameter(':tit',$titre);
        return $qry->getResult();
    }
    public function SelectMyBri($x){
        $qry=$this->getEntityManager()
            ->createQuery("SELECT m FROM volontaireBundle:volontaire m WHERE m.cin = :x")
            ->setParameter(':x',$x);
        return $qry->getResult();
    }
  /*  function Recherchebytit($key){
        $query = $this->createQueryBuilder('p')
            ->where('p.tireBri LIKE :key')
            ->setParameter(':key' , '%'.$key.'%')->getQuery();
        return $query->getResult();
    }*/




}
