<?php

namespace volontaireBundle\Repository;

/**
 * volontaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class volontaireRepository extends \Doctrine\ORM\EntityRepository
{
}
