p:
    resource: "@PBundle/Resources/config/routing.yml"
    prefix:   /p

refugie:
    resource: "@RefugieBundle/Resources/config/routing.yml"
    prefix:   /refugie

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

gcamp:
    resource: "@GcampBundle/Resources/config/routing.yml"
    prefix:   /gcamp

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# routing.yml / routes.yaml

fos_message:
  resource: "@FOSMessageBundle/Resources/config/routing.xml"
  prefix: /inbox


volontaire:
    resource: "@volontaireBundle/Resources/config/routing.yml"
    prefix:   /volentaire

discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /

Forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /frm
