# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CLIENT: ROLE_USER
        ROLE_AGENT:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_Docteur: ROLE_USER
        ROLE_Partenaire: ROLE_USER
        ROLE_RespCamp: ROLE_USER
        ROLE_MODERATOR: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /login
            anonymous:    true
            logout:
                target: /login






    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/affichage, role: ROLE_CLIENT }
        - { path: ^:/acceuilBack, role: ROLE_AGENT }
