<?php

namespace ForumBundle\Repository;

/**
 * CassocialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CassocialeRepository extends \Doctrine\ORM\EntityRepository
{
}
