<?php

namespace GcampBundle\Repository;

/**
 * BesoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinsRepository extends \Doctrine\ORM\EntityRepository
{

    function bs($id)
    {
        $query=$this->getEntityManager()
            ->createQuery(' Select B.nomBs , B.quantite FROM GcampBundle:camp A , GcampBundle:besoins B  where B.id_c=A.id and B.id_c=:id')
            ->setParameters(array('id'=>$id));
        return $query->getResult();

    }
    function somme($id)
    {
        $query=$this->getEntityManager()
            ->createQuery(' Select SUM( B.quantite) FROM GcampBundle:camp A , GcampBundle:besoins B  where B.id_c=A.id and B.id_c=:id')
            ->setParameters(array('id'=>$id));
        return $query->getResult();

    }
}
