<?php

namespace GcampBundle\Repository;



/**
 * CordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CordRepository extends \Doctrine\ORM\EntityRepository
{
    public function latt($id){
        $query=$this->getEntityManager()
            ->createQuery('select c.latitude , c.longitude  from GcampBundle:Cord c , GcampBundle:Camp e where e.lieu=c.id and e.id=:id ')
            ->setParameters(array('id'=>$id));
        return $query->getResult();
    }


}
